'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class HashJSON(typing.TypedDict):
    data: list[int]

@dataclass
class Hash:
    layout: typing.ClassVar = borsh.CStruct(
        "data" /borsh.U8[32],
        )
    #fields
    data: list[int]
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "Hash":
        return cls(
        data=obj["data"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "data": self.data,
                }

    def to_json(self) -> HashJSON:
        return {
                "data": self.data,
                }

    @classmethod
    def from_json(cls, obj: HashJSON) -> "Hash":
        return cls(
                data=obj["data"],
        )






