'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh;
import typing;
from anchorpy.borsh_extension import BorshPubkey;
from anchorpy.coder.accounts import ACCOUNT_DISCRIMINATOR_SIZE;
from anchorpy.error import AccountInvalidDiscriminator;
from anchorpy.utils.rpc import get_multiple_accounts;
from dataclasses import dataclass;
from solana.rpc.async_api import AsyncClient;
from solana.rpc.commitment import Commitment;
from solana.rpc.types import MemcmpOpts;
from solders.pubkey import Pubkey;
from ..program_id import PROGRAM_ID;


class HighLeverageModeConfigJSON(typing.TypedDict):
    maxUsers: int
    currentUsers: int
    reduceOnly: int
    padding: list[int]

@dataclass
class HighLeverageModeConfig:
    discriminator: typing.ClassVar = b"\x03\xc4\x5a\xbd\xc1\x40\xe4\xea";

    layout: typing.ClassVar = borsh.CStruct(
        "maxUsers" /borsh.U32,
        "currentUsers" /borsh.U32,
        "reduceOnly" /borsh.U8,
        "padding" /borsh.U8[31],
        )
    #fields
    maxUsers: int
    currentUsers: int
    reduceOnly: int
    padding: list[int]
    

    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PROGRAM_ID,
    ) -> typing.Optional["HighLeverageModeConfig"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PROGRAM_ID,
    ) -> typing.List[typing.Optional["HighLeverageModeConfig"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["HighLeverageModeConfig"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "HighLeverageModeConfig":
        if data[:ACCOUNT_DISCRIMINATOR_SIZE] != cls.discriminator:
            raise AccountInvalidDiscriminator(
                "The discriminator for this account is invalid"
            )
        dec = HighLeverageModeConfig.layout.parse(data[ACCOUNT_DISCRIMINATOR_SIZE:])
        return cls(
                maxUsers=dec.maxUsers,
                currentUsers=dec.currentUsers,
                reduceOnly=dec.reduceOnly,
                padding=dec.padding,
                )

    def to_json(self) -> HighLeverageModeConfigJSON:
        return {
                "maxUsers": self.maxUsers,
                "currentUsers": self.currentUsers,
                "reduceOnly": self.reduceOnly,
                "padding": self.padding,
                }

    @classmethod
    def from_json(cls, obj: HighLeverageModeConfigJSON) -> "HighLeverageModeConfig":
        return cls(
                maxUsers=obj["maxUsers"],
                currentUsers=obj["currentUsers"],
                reduceOnly=obj["reduceOnly"],
                padding=obj["padding"],
                )




