'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.error import AccountInvalidDiscriminator
from anchorpy.utils.rpc import get_multiple_accounts
from dataclasses import dataclass
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Commitment
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID


class ProtectedMakerModeConfigJSON(typing.TypedDict):
    maxUsers: int
    currentUsers: int
    reduceOnly: int
    padding: list[int]

@dataclass
class ProtectedMakerModeConfig:
    #fields
    maxUsers: int
    currentUsers: int
    reduceOnly: int
    padding: list[int]

    discriminator: typing.ClassVar = b"\x2f\x56\x5a\x09\xe0\xff\x0a\x45"
    DISCRIMINATOR_SIZE: int = 8

    layout: typing.ClassVar = borsh.CStruct(
        "maxUsers" /borsh.U32,
        "currentUsers" /borsh.U32,
        "reduceOnly" /borsh.U8,
        "padding" /borsh.U8[31],
        )



    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PROGRAM_ID,
    ) -> typing.Optional["ProtectedMakerModeConfig"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PROGRAM_ID,
    ) -> typing.List[typing.Optional["ProtectedMakerModeConfig"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["ProtectedMakerModeConfig"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "ProtectedMakerModeConfig":
        if data[:cls.DISCRIMINATOR_SIZE] != cls.discriminator:
            raise AccountInvalidDiscriminator(
                "The discriminator for this account is invalid"
            )
        dec = ProtectedMakerModeConfig.layout.parse(data[cls.DISCRIMINATOR_SIZE:])
        return cls(
                maxUsers=dec.maxUsers,
                currentUsers=dec.currentUsers,
                reduceOnly=dec.reduceOnly,
                padding=dec.padding,
                )

    def to_json(self) -> ProtectedMakerModeConfigJSON:
        return {
                "maxUsers": self.maxUsers,
                "currentUsers": self.currentUsers,
                "reduceOnly": self.reduceOnly,
                "padding": self.padding,
                }

    @classmethod
    def from_json(cls, obj: ProtectedMakerModeConfigJSON) -> "ProtectedMakerModeConfig":
        return cls(
                maxUsers=obj["maxUsers"],
                currentUsers=obj["currentUsers"],
                reduceOnly=obj["reduceOnly"],
                padding=obj["padding"],
                )




