'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.error import AccountInvalidDiscriminator
from anchorpy.utils.rpc import get_multiple_accounts
from dataclasses import dataclass
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Commitment
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID


class PythLazerOracleJSON(typing.TypedDict):
    price: int
    publishTime: int
    postedSlot: int
    exponent: int
    padding: list[int]
    conf: int

@dataclass
class PythLazerOracle:
    #fields
    price: int
    publishTime: int
    postedSlot: int
    exponent: int
    padding: list[int]
    conf: int

    discriminator: typing.ClassVar = b"\x9f\x07\xa1\xf9\x22\x51\x79\x85"
    DISCRIMINATOR_SIZE: int = 8

    layout: typing.ClassVar = borsh.CStruct(
        "price" /borsh.I64,
        "publishTime" /borsh.U64,
        "postedSlot" /borsh.U64,
        "exponent" /borsh.I32,
        "padding" /borsh.U8[4],
        "conf" /borsh.U64,
        )



    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PROGRAM_ID,
    ) -> typing.Optional["PythLazerOracle"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PROGRAM_ID,
    ) -> typing.List[typing.Optional["PythLazerOracle"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["PythLazerOracle"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "PythLazerOracle":
        if data[:cls.DISCRIMINATOR_SIZE] != cls.discriminator:
            raise AccountInvalidDiscriminator(
                "The discriminator for this account is invalid"
            )
        dec = PythLazerOracle.layout.parse(data[cls.DISCRIMINATOR_SIZE:])
        return cls(
                price=dec.price,
                publishTime=dec.publishTime,
                postedSlot=dec.postedSlot,
                exponent=dec.exponent,
                padding=dec.padding,
                conf=dec.conf,
                )

    def to_json(self) -> PythLazerOracleJSON:
        return {
                "price": self.price,
                "publishTime": self.publishTime,
                "postedSlot": self.postedSlot,
                "exponent": self.exponent,
                "padding": self.padding,
                "conf": self.conf,
                }

    @classmethod
    def from_json(cls, obj: PythLazerOracleJSON) -> "PythLazerOracle":
        return cls(
                price=obj["price"],
                publishTime=obj["publishTime"],
                postedSlot=obj["postedSlot"],
                exponent=obj["exponent"],
                padding=obj["padding"],
                conf=obj["conf"],
                )




