'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class CancelOrderByUserIdArgs(typing.TypedDict):
    userOrderId:int


layout = borsh.CStruct(
    "userOrderId" /borsh.U8,
    )


class CancelOrderByUserIdAccounts(typing.TypedDict):
    state:SolPubkey
    user:SolPubkey
    authority:SolPubkey

def CancelOrderByUserId(
    args: CancelOrderByUserIdArgs,
    accounts: CancelOrderByUserIdAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["user"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["authority"], is_signer=True, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x6b\xd3\xfa\x85\x12\x25\x39\x64"
    encoded_args = layout.build({
        "userOrderId":args["userOrderId"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




