'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class CancelRequestRemoveInsuranceFundStakeArgs(typing.TypedDict):
    marketIndex:int


layout = borsh.CStruct(
    "marketIndex" /borsh.U16,
    )


class CancelRequestRemoveInsuranceFundStakeAccounts(typing.TypedDict):
    spotMarket:SolPubkey
    insuranceFundStake:SolPubkey
    userStats:SolPubkey
    authority:SolPubkey
    insuranceFundVault:SolPubkey

def CancelRequestRemoveInsuranceFundStake(
    args: CancelRequestRemoveInsuranceFundStakeArgs,
    accounts: CancelRequestRemoveInsuranceFundStakeAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["spotMarket"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["insuranceFundStake"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["userStats"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["authority"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["insuranceFundVault"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x61\xeb\x4e\x3e\xd4\x2a\xf1\x7f"
    encoded_args = layout.build({
        "marketIndex":args["marketIndex"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




