'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh;
import typing;
from construct import Container;
from dataclasses import dataclass;
from solders.instruction import AccountMeta, Instruction;
from solders.pubkey import Pubkey;
from solders.sysvar import RENT;
from ..program_id import PROGRAM_ID;
class CancelOrdersArgs(typing.TypedDict):
    marketType:typing.Optional[types.marketType.MarketTypeJSON]
    marketIndex:typing.Optional[int]
    direction:typing.Optional[types.positionDirection.PositionDirectionJSON]


layout = borsh.CStruct(
    "marketType" /borsh.Option(types.marketType.MarketType.layout),
    "marketIndex" /borsh.Option(borsh.U16),
    "direction" /borsh.Option(types.positionDirection.PositionDirection.layout),
    )


class CancelOrdersAccounts(typing.TypedDict):
    state:Pubkey
    user:Pubkey
    authority:Pubkey

def CancelOrders(
    args: CancelOrdersArgs,
    accounts: CancelOrdersAccounts,
    program_id: Pubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["user"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["authority"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=RENT, is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xee\xe1\x5f\x9e\xe3\x67\x08\xc2"
    encoded_args = layout.build({
    "marketType":args["marketType"],
    "marketIndex":args["marketIndex"],
    "direction":args["direction"],
       })

    data = identifier + encoded_args
    return Instruction(program_id,data,keys)

