'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class DeletePrelaunchOracleArgs(typing.TypedDict):
    perpMarketIndex:int


layout = borsh.CStruct(
    "perpMarketIndex" /borsh.U16,
    )


class DeletePrelaunchOracleAccounts(typing.TypedDict):
    admin:SolPubkey
    prelaunchOracle:SolPubkey
    perpMarket:SolPubkey
    state:SolPubkey

def DeletePrelaunchOracle(
    args: DeletePrelaunchOracleArgs,
    accounts: DeletePrelaunchOracleAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["prelaunchOracle"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["perpMarket"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x3b\xa9\x64\x31\x45\x11\xad\xfd"
    encoded_args = layout.build({
        "perpMarketIndex":args["perpMarketIndex"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



