'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import PROGRAM_ID
class ModifyOrderArgs(typing.TypedDict):
    orderId:typing.Optional[int]
    modifyOrderParams:types.modifyOrderParams.ModifyOrderParams


layout = borsh.CStruct(
    "orderId" /borsh.Option(borsh.U32),
    "modifyOrderParams" /types.modifyOrderParams.ModifyOrderParams.layout,
    )


class ModifyOrderAccounts(typing.TypedDict):
    state:SolPubkey
    user:SolPubkey
    authority:SolPubkey

def ModifyOrder(
    args: ModifyOrderArgs,
    accounts: ModifyOrderAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["user"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["authority"], is_signer=True, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x2f\x7c\x75\xff\xc9\xc5\x82\x5e"
    encoded_args = layout.build({
        "orderId":args["orderId"],
        "modifyOrderParams":args["modifyOrderParams"].to_encodable(),
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




