'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class MoveAmmPriceArgs(typing.TypedDict):
    baseAssetReserve:int
    quoteAssetReserve:int
    sqrtK:int


layout = borsh.CStruct(
    "baseAssetReserve" /borsh.U128,
    "quoteAssetReserve" /borsh.U128,
    "sqrtK" /borsh.U128,
    )


class MoveAmmPriceAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey
    perpMarket:SolPubkey

def MoveAmmPrice(
    args: MoveAmmPriceArgs,
    accounts: MoveAmmPriceAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["perpMarket"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xeb\x6d\x02\x52\xdb\x76\x06\x9f"
    encoded_args = layout.build({
        "baseAssetReserve":args["baseAssetReserve"],
        "quoteAssetReserve":args["quoteAssetReserve"],
        "sqrtK":args["sqrtK"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



