'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class RecenterPerpMarketAmmArgs(typing.TypedDict):
    pegMultiplier:int
    sqrtK:int


layout = borsh.CStruct(
    "pegMultiplier" /borsh.U128,
    "sqrtK" /borsh.U128,
    )


class RecenterPerpMarketAmmAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey
    perpMarket:SolPubkey

def RecenterPerpMarketAmm(
    args: RecenterPerpMarketAmmArgs,
    accounts: RecenterPerpMarketAmmAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["perpMarket"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x18\x57\x0a\x73\xa5\xbe\x50\x8b"
    encoded_args = layout.build({
        "pegMultiplier":args["pegMultiplier"],
        "sqrtK":args["sqrtK"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



