'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class ResolveSpotBankruptcyArgs(typing.TypedDict):
    marketIndex:int


layout = borsh.CStruct(
    "marketIndex" /borsh.U16,
    )


class ResolveSpotBankruptcyAccounts(typing.TypedDict):
    state:SolPubkey
    authority:SolPubkey
    liquidator:SolPubkey
    liquidatorStats:SolPubkey
    user:SolPubkey
    userStats:SolPubkey
    spotMarketVault:SolPubkey
    insuranceFundVault:SolPubkey
    driftSigner:SolPubkey
    tokenProgram:SolPubkey

def ResolveSpotBankruptcy(
    args: ResolveSpotBankruptcyArgs,
    accounts: ResolveSpotBankruptcyAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["authority"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["liquidator"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["liquidatorStats"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["user"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["userStats"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["spotMarketVault"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["insuranceFundVault"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["driftSigner"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["tokenProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x7c\xc2\xf0\xfe\xc6\xd5\x34\x7a"
    encoded_args = layout.build({
        "marketIndex":args["marketIndex"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)






