'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh;
import typing;
from construct import Container;
from dataclasses import dataclass;
from solders.instruction import AccountMeta, Instruction;
from solders.pubkey import Pubkey;
from solders.sysvar import RENT;
from .. import types;
from ..program_id import PROGRAM_ID;
class SettleMultiplePnlsArgs(typing.TypedDict):
    marketIndexes:list[int]
    mode:types.settlePnlMode.SettlePnlModeKind


layout = borsh.CStruct(
    "marketIndexes" /borsh.U16[0],
    "mode" /types.settlePnlMode.layout,
    )


class SettleMultiplePnlsAccounts(typing.TypedDict):
    state:Pubkey
    user:Pubkey
    authority:Pubkey
    spotMarketVault:Pubkey

def SettleMultiplePnls(
    args: SettleMultiplePnlsArgs,
    accounts: SettleMultiplePnlsAccounts,
    program_id: Pubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["user"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["authority"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["spotMarketVault"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=RENT, is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x7f\x42\x75\x39\x28\x32\x98\x7f"
    encoded_args = layout.build({
    "marketIndexes":args["marketIndexes"],
    "mode":args["mode"],
       })

    data = identifier + encoded_args
    return Instruction(program_id,data,keys)

