'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class TriggerOrderArgs(typing.TypedDict):
    orderId:int


layout = borsh.CStruct(
    "orderId" /borsh.U32,
    )


class TriggerOrderAccounts(typing.TypedDict):
    state:SolPubkey
    authority:SolPubkey
    filler:SolPubkey
    user:SolPubkey

def TriggerOrder(
    args: TriggerOrderArgs,
    accounts: TriggerOrderAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["authority"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["filler"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["user"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x3f\x70\x33\xe9\xe8\x2f\xf0\xc7"
    encoded_args = layout.build({
        "orderId":args["orderId"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




