'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateFundingRateArgs(typing.TypedDict):
    marketIndex:int


layout = borsh.CStruct(
    "marketIndex" /borsh.U16,
    )


class UpdateFundingRateAccounts(typing.TypedDict):
    state:SolPubkey
    perpMarket:SolPubkey
    oracle:SolPubkey

def UpdateFundingRate(
    args: UpdateFundingRateArgs,
    accounts: UpdateFundingRateAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["perpMarket"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["oracle"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xc9\xb2\x74\xd4\xa6\x90\x48\xee"
    encoded_args = layout.build({
        "marketIndex":args["marketIndex"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



