'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateSpotMarketLiquidationFeeArgs(typing.TypedDict):
    liquidatorFee:int
    ifLiquidationFee:int


layout = borsh.CStruct(
    "liquidatorFee" /borsh.U32,
    "ifLiquidationFee" /borsh.U32,
    )


class UpdateSpotMarketLiquidationFeeAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey
    spotMarket:SolPubkey

def UpdateSpotMarketLiquidationFee(
    args: UpdateSpotMarketLiquidationFeeArgs,
    accounts: UpdateSpotMarketLiquidationFeeAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["spotMarket"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x0b\x0d\xff\x35\x38\x88\x68\xb1"
    encoded_args = layout.build({
        "liquidatorFee":args["liquidatorFee"],
        "ifLiquidationFee":args["ifLiquidationFee"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



