'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateSpotAuctionDurationArgs(typing.TypedDict):
    defaultSpotAuctionDuration:int


layout = borsh.CStruct(
    "defaultSpotAuctionDuration" /borsh.U8,
    )


class UpdateSpotAuctionDurationAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey

def UpdateSpotAuctionDuration(
    args: UpdateSpotAuctionDurationArgs,
    accounts: UpdateSpotAuctionDurationAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xb6\xb2\xcb\x48\xbb\x8f\x9d\x6b"
    encoded_args = layout.build({
        "defaultSpotAuctionDuration":args["defaultSpotAuctionDuration"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



