'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateSpotMarketOrdersEnabledArgs(typing.TypedDict):
    ordersEnabled:bool


layout = borsh.CStruct(
    "ordersEnabled" /borsh.Bool,
    )


class UpdateSpotMarketOrdersEnabledAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey
    spotMarket:SolPubkey

def UpdateSpotMarketOrdersEnabled(
    args: UpdateSpotMarketOrdersEnabledArgs,
    accounts: UpdateSpotMarketOrdersEnabledAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["spotMarket"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xbe\x4f\xce\x0f\x1a\xe5\xe5\x2b"
    encoded_args = layout.build({
        "ordersEnabled":args["ordersEnabled"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



