'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateDiscountMintArgs(typing.TypedDict):
    discountMint:SolPubkey


layout = borsh.CStruct(
    "discountMint" /BorshPubkey,
    )


class UpdateDiscountMintAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey

def UpdateDiscountMint(
    args: UpdateDiscountMintArgs,
    accounts: UpdateDiscountMintAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x20\xfc\x7a\xd3\x42\x1f\x2f\xf1"
    encoded_args = layout.build({
        "discountMint":args["discountMint"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



