'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateExchangeStatusArgs(typing.TypedDict):
    exchangeStatus:int


layout = borsh.CStruct(
    "exchangeStatus" /borsh.U8,
    )


class UpdateExchangeStatusAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey

def UpdateExchangeStatus(
    args: UpdateExchangeStatusArgs,
    accounts: UpdateExchangeStatusAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x53\xa0\xfc\xfa\x81\x74\x31\xdf"
    encoded_args = layout.build({
        "exchangeStatus":args["exchangeStatus"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



