'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID

class UpdatePerpBidAskTwapAccounts(typing.TypedDict):
    state:SolPubkey
    perpMarket:SolPubkey
    oracle:SolPubkey
    keeperStats:SolPubkey
    authority:SolPubkey

def UpdatePerpBidAskTwap(
    accounts: UpdatePerpBidAskTwapAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["perpMarket"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["oracle"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["keeperStats"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["authority"], is_signer=True, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xf7\x17\xff\x41\xd4\x5a\xdd\xc2"
    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




