'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import PROGRAM_ID
class UpdateSpotFeeStructureArgs(typing.TypedDict):
    feeStructure:types.feeStructure.FeeStructure


layout = borsh.CStruct(
    "feeStructure" /types.feeStructure.FeeStructure.layout,
    )


class UpdateSpotFeeStructureAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey

def UpdateSpotFeeStructure(
    args: UpdateSpotFeeStructureArgs,
    accounts: UpdateSpotFeeStructureAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x61\xd8\x69\x83\x71\xf6\x8e\x8d"
    encoded_args = layout.build({
        "feeStructure":args["feeStructure"].to_encodable(),
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



