'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID

class UpdatePerpMarketAmmOracleTwapAccounts(typing.TypedDict):
    state:SolPubkey
    perpMarket:SolPubkey
    oracle:SolPubkey
    admin:SolPubkey

def UpdatePerpMarketAmmOracleTwap(
    accounts: UpdatePerpMarketAmmOracleTwapAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["perpMarket"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["oracle"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xf1\x4a\x72\x7b\xce\x99\x18\xca"
    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



