'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh;
import typing;
from construct import Container;
from dataclasses import dataclass;
from solders.instruction import AccountMeta, Instruction;
from solders.pubkey import Pubkey;
from solders.sysvar import RENT;
from ..program_id import PROGRAM_ID;
class UpdateUserMarginTradingEnabledArgs(typing.TypedDict):
    subAccountId:int
    marginTradingEnabled:bool


layout = borsh.CStruct(
    "subAccountId" /borsh.U16,
    "marginTradingEnabled" /borsh.Bool,
    )


class UpdateUserMarginTradingEnabledAccounts(typing.TypedDict):
    user:Pubkey
    authority:Pubkey

def UpdateUserMarginTradingEnabled(
    args: UpdateUserMarginTradingEnabledArgs,
    accounts: UpdateUserMarginTradingEnabledAccounts,
    program_id: Pubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["user"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["authority"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=RENT, is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xc2\x5c\xcc\xdf\xf6\xbc\x1f\xcb"
    encoded_args = layout.build({
    "subAccountId":args["subAccountId"],
    "marginTradingEnabled":args["marginTradingEnabled"],
       })

    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



