'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID

class UpdateSpotMarketCumulativeInterestAccounts(typing.TypedDict):
    state:SolPubkey
    spotMarket:SolPubkey
    oracle:SolPubkey
    spotMarketVault:SolPubkey

def UpdateSpotMarketCumulativeInterest(
    accounts: UpdateSpotMarketCumulativeInterestAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["spotMarket"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["oracle"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["spotMarketVault"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x27\xa6\x8b\xf3\x9e\xa5\x9b\xe1"
    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



