'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdatePerpMarketMaxSpreadArgs(typing.TypedDict):
    maxSpread:int


layout = borsh.CStruct(
    "maxSpread" /borsh.U32,
    )


class UpdatePerpMarketMaxSpreadAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey
    perpMarket:SolPubkey

def UpdatePerpMarketMaxSpread(
    args: UpdatePerpMarketMaxSpreadArgs,
    accounts: UpdatePerpMarketMaxSpreadAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["perpMarket"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x50\xfc\x7a\x3e\x28\xda\x5b\x64"
    encoded_args = layout.build({
        "maxSpread":args["maxSpread"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



