'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateAdminArgs(typing.TypedDict):
    admin:SolPubkey


layout = borsh.CStruct(
    "admin" /BorshPubkey,
    )


class UpdateAdminAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey

def UpdateAdmin(
    args: UpdateAdminArgs,
    accounts: UpdateAdminAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xa1\xb0\x28\xd5\x3c\xb8\xb3\xe4"
    encoded_args = layout.build({
        "admin":args["admin"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



