'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdatePerpMarketPerLpBaseArgs(typing.TypedDict):
    perLpBase:int


layout = borsh.CStruct(
    "perLpBase" /borsh.I8,
    )


class UpdatePerpMarketPerLpBaseAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey
    perpMarket:SolPubkey

def UpdatePerpMarketPerLpBase(
    args: UpdatePerpMarketPerLpBaseArgs,
    accounts: UpdatePerpMarketPerLpBaseAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["perpMarket"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x67\x98\x67\x66\x59\x90\xc1\x47"
    encoded_args = layout.build({
        "perLpBase":args["perLpBase"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



