'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateUserCustomMarginRatioArgs(typing.TypedDict):
    subAccountId:int
    marginRatio:int


layout = borsh.CStruct(
    "subAccountId" /borsh.U16,
    "marginRatio" /borsh.U32,
    )


class UpdateUserCustomMarginRatioAccounts(typing.TypedDict):
    user:SolPubkey
    authority:SolPubkey

def UpdateUserCustomMarginRatio(
    args: UpdateUserCustomMarginRatioArgs,
    accounts: UpdateUserCustomMarginRatioAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["user"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["authority"], is_signer=True, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x15\xdd\x8c\xbb\x20\x81\x0b\x7b"
    encoded_args = layout.build({
        "subAccountId":args["subAccountId"],
        "marginRatio":args["marginRatio"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




