'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateWhitelistMintArgs(typing.TypedDict):
    whitelistMint:SolPubkey


layout = borsh.CStruct(
    "whitelistMint" /BorshPubkey,
    )


class UpdateWhitelistMintAccounts(typing.TypedDict):
    admin:SolPubkey
    state:SolPubkey

def UpdateWhitelistMint(
    args: UpdateWhitelistMintArgs,
    accounts: UpdateWhitelistMintAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["state"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xa1\x0f\xa2\x13\x94\x78\x90\x97"
    encoded_args = layout.build({
        "whitelistMint":args["whitelistMint"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



