'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from anchorpy.error import AccountInvalidDiscriminator
from anchorpy.utils.rpc import get_multiple_accounts
from dataclasses import dataclass
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Commitment
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import PROGRAM_ID


class OracleTwapsJSON(typing.TypedDict):
    oraclePrices: str
    oracleMappings: str
    twaps: list[types.emaTwap.EmaTwapJSON]

@dataclass
class OracleTwaps:
    #fields
    oraclePrices: SolPubkey
    oracleMappings: SolPubkey
    twaps: list[types.emaTwap.EmaTwap]

    discriminator: typing.ClassVar = b"\xc0\x8b\x1b\xfa\x35\xa6\x65\x3d"
    DISCRIMINATOR_SIZE: int = 8

    layout: typing.ClassVar = borsh.CStruct(
        "oraclePrices" /BorshPubkey,
        "oracleMappings" /BorshPubkey,
        "twaps" /types.emaTwap.EmaTwap.layout[512],
        )



    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PROGRAM_ID,
    ) -> typing.Optional["OracleTwaps"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PROGRAM_ID,
    ) -> typing.List[typing.Optional["OracleTwaps"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["OracleTwaps"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "OracleTwaps":
        if data[:cls.DISCRIMINATOR_SIZE] != cls.discriminator:
            raise AccountInvalidDiscriminator(
                "The discriminator for this account is invalid"
            )
        dec = OracleTwaps.layout.parse(data[cls.DISCRIMINATOR_SIZE:])
        return cls(
                oraclePrices=dec.oraclePrices,
                oracleMappings=dec.oracleMappings,
                twaps=dec.twaps,
                )

    def to_json(self) -> OracleTwapsJSON:
        return {
                "oraclePrices": str(self.oraclePrices),
                "oracleMappings": str(self.oracleMappings),
                "twaps": list(map(lambda item:item.to_json(),self.twaps)),
                }

    @classmethod
    def from_json(cls, obj: OracleTwapsJSON) -> "OracleTwaps":
        return cls(
                oraclePrices=SolPubkey.from_string(obj["oraclePrices"]),
                oracleMappings=SolPubkey.from_string(obj["oracleMappings"]),
                twaps=list(map(lambda item:types.emaTwap.EmaTwap.from_json(item),obj["twaps"])),
                )




