'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh;
import typing;
from anchorpy.borsh_extension import BorshPubkey;
from construct import Container;
from dataclasses import dataclass;
from solders.pubkey import Pubkey;
from solders.sysvar import RENT;

class ExtendAccountEventJSON(typing.TypedDict):
    timestamp: int
    account: str
    user: str
    currentSize: int
    newSize: int

@dataclass
class ExtendAccountEvent:
    layout: typing.ClassVar = borsh.CStruct(
        "timestamp" /borsh.I64,
        "account" /BorshPubkey,
        "user" /BorshPubkey,
        "currentSize" /borsh.U64,
        "newSize" /borsh.U64,
        )
    #fields
    timestamp: int
    account: Pubkey
    user: Pubkey
    currentSize: int
    newSize: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "ExtendAccountEvent":
        return cls(
        timestamp=obj["timestamp"],
        account=Pubkey.from_string(obj["account"]),
        user=Pubkey.from_string(obj["user"]),
        currentSize=obj["currentSize"],
        newSize=obj["newSize"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "timestamp": self.timestamp,
                "account": self.account,
                "user": self.user,
                "currentSize": self.currentSize,
                "newSize": self.newSize,
                }

    def to_json(self) -> ExtendAccountEventJSON:
        return {
                "timestamp": self.timestamp,
                "account": str(self.account),
                "user": str(self.user),
                "currentSize": self.currentSize,
                "newSize": self.newSize,
                }

    @classmethod
    def from_json(cls, obj: ExtendAccountEventJSON) -> "ExtendAccountEvent":
        return cls(
                timestamp=obj["timestamp"],
                account=Pubkey.from_string(obj["account"]),
                user=Pubkey.from_string(obj["user"]),
                currentSize=obj["currentSize"],
                newSize=obj["newSize"],
        )






