'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class ResetTwapArgs(typing.TypedDict):
    token:int
    feedName:str


layout = borsh.CStruct(
    "token" /borsh.U64,
    "feedName" /borsh.String,
    )


class ResetTwapAccounts(typing.TypedDict):
    admin:SolPubkey
    configuration:SolPubkey
    oracleTwaps:SolPubkey
    instructionSysvarAccountInfo:SolPubkey

def ResetTwap(
    args: ResetTwapArgs,
    accounts: ResetTwapAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["configuration"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["oracleTwaps"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["instructionSysvarAccountInfo"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x65\xd8\x1c\x5c\x9a\x4f\x31\xbb"
    encoded_args = layout.build({
        "token":args["token"],
        "feedName":args["feedName"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



