'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey

class CompleteEventJSON(typing.TypedDict):
    user: str
    mint: str
    bondingCurve: str
    timestamp: int

@dataclass
class CompleteEvent:
    layout: typing.ClassVar = borsh.CStruct(
        "user" /BorshPubkey,
        "mint" /BorshPubkey,
        "bondingCurve" /BorshPubkey,
        "timestamp" /borsh.I64,
        )
    #fields
    user: SolPubkey
    mint: SolPubkey
    bondingCurve: SolPubkey
    timestamp: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "CompleteEvent":
        return cls(
        user=obj["user"],
        mint=obj["mint"],
        bondingCurve=obj["bondingCurve"],
        timestamp=obj["timestamp"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "user": self.user,
                "mint": self.mint,
                "bondingCurve": self.bondingCurve,
                "timestamp": self.timestamp,
                }

    def to_json(self) -> CompleteEventJSON:
        return {
                "user": str(self.user),
                "mint": str(self.mint),
                "bondingCurve": str(self.bondingCurve),
                "timestamp": self.timestamp,
                }

    @classmethod
    def from_json(cls, obj: CompleteEventJSON) -> "CompleteEvent":
        return cls(
                user=SolPubkey.from_string(obj["user"]),
                mint=SolPubkey.from_string(obj["mint"]),
                bondingCurve=SolPubkey.from_string(obj["bondingCurve"]),
                timestamp=obj["timestamp"],
        )






