'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey

class SetMetaplexCreatorEventJSON(typing.TypedDict):
    timestamp: int
    mint: str
    bondingCurve: str
    metadata: str
    creator: str

@dataclass
class SetMetaplexCreatorEvent:
    layout: typing.ClassVar = borsh.CStruct(
        "timestamp" /borsh.I64,
        "mint" /BorshPubkey,
        "bondingCurve" /BorshPubkey,
        "metadata" /BorshPubkey,
        "creator" /BorshPubkey,
        )
    #fields
    timestamp: int
    mint: SolPubkey
    bondingCurve: SolPubkey
    metadata: SolPubkey
    creator: SolPubkey
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "SetMetaplexCreatorEvent":
        return cls(
        timestamp=obj["timestamp"],
        mint=obj["mint"],
        bondingCurve=obj["bondingCurve"],
        metadata=obj["metadata"],
        creator=obj["creator"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "timestamp": self.timestamp,
                "mint": self.mint,
                "bondingCurve": self.bondingCurve,
                "metadata": self.metadata,
                "creator": self.creator,
                }

    def to_json(self) -> SetMetaplexCreatorEventJSON:
        return {
                "timestamp": self.timestamp,
                "mint": str(self.mint),
                "bondingCurve": str(self.bondingCurve),
                "metadata": str(self.metadata),
                "creator": str(self.creator),
                }

    @classmethod
    def from_json(cls, obj: SetMetaplexCreatorEventJSON) -> "SetMetaplexCreatorEvent":
        return cls(
                timestamp=obj["timestamp"],
                mint=SolPubkey.from_string(obj["mint"]),
                bondingCurve=SolPubkey.from_string(obj["bondingCurve"]),
                metadata=SolPubkey.from_string(obj["metadata"]),
                creator=SolPubkey.from_string(obj["creator"]),
        )






