'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID

class CreateAssociatedTokenAccounts(typing.TypedDict):
    payer:SolPubkey
    ata:SolPubkey
    owner:SolPubkey
    mint:SolPubkey
    systemProgram:SolPubkey
    tokenProgram:SolPubkey

def CreateAssociatedToken(
    accounts: CreateAssociatedTokenAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["payer"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["ata"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["owner"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["mint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["systemProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["tokenProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x00"
    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




def find_Ata() -> typing.Tuple[SolPubkey, int]:
    seeds = [
    ]

    address, bump = SolPubkey.find_program_address(seeds,
        PROGRAM_ID
            )

    return address, bump







