'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import TOKEN_2022_PROGRAM_ADDRESS
from ..shared import ZeroableOption
class InitializeConfidentialTransferFeeArgs(typing.TypedDict):
    confidentialTransferFeeDiscriminator:int
    authority:SolPubkey
    withdrawWithheldAuthorityElGamalPubkey:SolPubkey


layout = borsh.CStruct(
    "confidentialTransferFeeDiscriminator" /borsh.U8,
    "authority" /ZeroableOption(BorshPubkey,None,"publicKey"),
    "withdrawWithheldAuthorityElGamalPubkey" /ZeroableOption(BorshPubkey,None,"publicKey"),
    )


class InitializeConfidentialTransferFeeAccounts(typing.TypedDict):
    mint:SolPubkey

def InitializeConfidentialTransferFee(
    args: InitializeConfidentialTransferFeeArgs,
    accounts: InitializeConfidentialTransferFeeAccounts,
    program_id: SolPubkey =  TOKEN_2022_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["mint"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x25"
    encoded_args = layout.build({
        "confidentialTransferFeeDiscriminator":args["confidentialTransferFeeDiscriminator"],
        "authority":args["authority"],
        "withdrawWithheldAuthorityElGamalPubkey":args["withdrawWithheldAuthorityElGamalPubkey"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



