'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Construct
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import TOKEN_2022_PROGRAM_ADDRESS
class ReallocateArgs(typing.TypedDict):
    newExtensionTypes:list[types.extensionType.ExtensionTypeKind]


layout = borsh.CStruct(
    "newExtensionTypes" /borsh.Vec(typing.cast(Construct, types.extensionType.layout)),
    )


class ReallocateAccounts(typing.TypedDict):
    token:SolPubkey
    payer:SolPubkey
    systemProgram:SolPubkey
    owner:SolPubkey

def Reallocate(
    args: ReallocateArgs,
    accounts: ReallocateAccounts,
    program_id: SolPubkey =  TOKEN_2022_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["token"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["payer"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["systemProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["owner"], is_signer=True, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x1d"
    encoded_args = layout.build({
        "newExtensionTypes":,
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




