'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import TOKEN_2022_PROGRAM_ADDRESS
from ..shared import ZeroableOption
class UpdateGroupPointerArgs(typing.TypedDict):
    groupPointerDiscriminator:int
    groupAddress:SolPubkey


layout = borsh.CStruct(
    "groupPointerDiscriminator" /borsh.U8,
    "groupAddress" /ZeroableOption(BorshPubkey,None),
    )


class UpdateGroupPointerAccounts(typing.TypedDict):
    mint:SolPubkey
    groupPointerAuthority:SolPubkey

def UpdateGroupPointer(
    args: UpdateGroupPointerArgs,
    accounts: UpdateGroupPointerAccounts,
    program_id: SolPubkey =  TOKEN_2022_PROGRAM_ADDRESS,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["mint"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["groupPointerAuthority"], is_signer=True, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x28"
    encoded_args = layout.build({
        "groupPointerDiscriminator":args["groupPointerDiscriminator"],
        "groupAddress":args["groupAddress"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



