'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateMultiplierScaledUiMintArgs(typing.TypedDict):
    scaledUiAmountMintDiscriminator:int
    multiplier:int
    effectiveTimestamp:int


layout = borsh.CStruct(
    "scaledUiAmountMintDiscriminator" /borsh.U8,
    "multiplier" /borsh.F64,
    "effectiveTimestamp" /borsh.I64,
    )


class UpdateMultiplierScaledUiMintAccounts(typing.TypedDict):
    mint:SolPubkey
    authority:SolPubkey

def UpdateMultiplierScaledUiMint(
    args: UpdateMultiplierScaledUiMintArgs,
    accounts: UpdateMultiplierScaledUiMintAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["mint"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["authority"], is_signer=True, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x2b"
    encoded_args = layout.build({
        "scaledUiAmountMintDiscriminator":args["scaledUiAmountMintDiscriminator"],
        "multiplier":args["multiplier"],
        "effectiveTimestamp":args["effectiveTimestamp"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



