'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class WithdrawWithheldTokensFromMintArgs(typing.TypedDict):
    transferFeeDiscriminator:int


layout = borsh.CStruct(
    "transferFeeDiscriminator" /borsh.U8,
    )


class WithdrawWithheldTokensFromMintAccounts(typing.TypedDict):
    mint:SolPubkey
    feeReceiver:SolPubkey
    withdrawWithheldAuthority:SolPubkey

def WithdrawWithheldTokensFromMint(
    args: WithdrawWithheldTokensFromMintArgs,
    accounts: WithdrawWithheldTokensFromMintAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["mint"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["feeReceiver"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["withdrawWithheldAuthority"], is_signer=True, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x1a"
    encoded_args = layout.build({
        "transferFeeDiscriminator":args["transferFeeDiscriminator"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




