'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID

class CreateTokenLedgerAccounts(typing.TypedDict):
    tokenLedger:SolPubkey
    payer:SolPubkey
    systemProgram:SolPubkey

def CreateTokenLedger(
    accounts: CreateTokenLedgerAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["tokenLedger"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["payer"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["systemProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xe8\xf2\xc5\xfd\xf0\x8f\x81\x34"
    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)






