'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Construct
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from .. import types
from ..program_id import PROGRAM_ID
class RouteWithTokenLedgerArgs(typing.TypedDict):
    routePlan:list[types.routePlanStep.RoutePlanStep]
    quotedOutAmount:int
    slippageBps:int
    platformFeeBps:int


layout = borsh.CStruct(
    "routePlan" /borsh.Vec(typing.cast(Construct, types.routePlanStep.RoutePlanStep.layout)),
    "quotedOutAmount" /borsh.U64,
    "slippageBps" /borsh.U16,
    "platformFeeBps" /borsh.U8,
    )


class RouteWithTokenLedgerAccounts(typing.TypedDict):
    tokenProgram:SolPubkey
    userTransferAuthority:SolPubkey
    userSourceTokenAccount:SolPubkey
    userDestinationTokenAccount:SolPubkey
    destinationTokenAccount:SolPubkey
    destinationMint:SolPubkey
    platformFeeAccount:SolPubkey
    tokenLedger:SolPubkey
    eventAuthority:SolPubkey
    program:SolPubkey

def RouteWithTokenLedger(
    args: RouteWithTokenLedgerArgs,
    accounts: RouteWithTokenLedgerAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["tokenProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["userTransferAuthority"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["userSourceTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["userDestinationTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["destinationTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["destinationMint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["platformFeeAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["tokenLedger"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["eventAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["program"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x96\x56\x47\x74\xa7\x5d\x0e\x68"
    encoded_args = layout.build({
        "routePlan":list(map(lambda item:item.to_encodable(),args["routePlan"])),
        "quotedOutAmount":args["quotedOutAmount"],
        "slippageBps":args["slippageBps"],
        "platformFeeBps":args["platformFeeBps"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)






