'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID

class SetTokenLedgerAccounts(typing.TypedDict):
    tokenLedger:SolPubkey
    tokenAccount:SolPubkey

def SetTokenLedger(
    accounts: SetTokenLedgerAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["tokenLedger"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["tokenAccount"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xe4\x55\xb9\x70\x4e\x4f\x4d\x02"
    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



