'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh;
import typing;
from anchorpy.borsh_extension import BorshPubkey, EnumForCodegen;
from construct import Container;
from dataclasses import dataclass;
from solders.pubkey import Pubkey;
from solders.sysvar import RENT;

class NoneJSON(typing.TypedDict):
    kind: typing.Literal["None"]


@dataclass
class None:
    discriminator: typing.ClassVar = 0
    @classmethod
    def to_json(cls) -> NoneJSON:
        return NoneJSON(
            kind="None",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "None": {},
        }



class InsufficientFreeCollateralJSON(typing.TypedDict):
    kind: typing.Literal["InsufficientFreeCollateral"]


@dataclass
class InsufficientFreeCollateral:
    discriminator: typing.ClassVar = 1
    @classmethod
    def to_json(cls) -> InsufficientFreeCollateralJSON:
        return InsufficientFreeCollateralJSON(
            kind="InsufficientFreeCollateral",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "InsufficientFreeCollateral": {},
        }



class OraclePriceBreachedLimitPriceJSON(typing.TypedDict):
    kind: typing.Literal["OraclePriceBreachedLimitPrice"]


@dataclass
class OraclePriceBreachedLimitPrice:
    discriminator: typing.ClassVar = 2
    @classmethod
    def to_json(cls) -> OraclePriceBreachedLimitPriceJSON:
        return OraclePriceBreachedLimitPriceJSON(
            kind="OraclePriceBreachedLimitPrice",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "OraclePriceBreachedLimitPrice": {},
        }



class MarketOrderFilledToLimitPriceJSON(typing.TypedDict):
    kind: typing.Literal["MarketOrderFilledToLimitPrice"]


@dataclass
class MarketOrderFilledToLimitPrice:
    discriminator: typing.ClassVar = 3
    @classmethod
    def to_json(cls) -> MarketOrderFilledToLimitPriceJSON:
        return MarketOrderFilledToLimitPriceJSON(
            kind="MarketOrderFilledToLimitPrice",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "MarketOrderFilledToLimitPrice": {},
        }



class OrderExpiredJSON(typing.TypedDict):
    kind: typing.Literal["OrderExpired"]


@dataclass
class OrderExpired:
    discriminator: typing.ClassVar = 4
    @classmethod
    def to_json(cls) -> OrderExpiredJSON:
        return OrderExpiredJSON(
            kind="OrderExpired",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "OrderExpired": {},
        }



class LiquidationJSON(typing.TypedDict):
    kind: typing.Literal["Liquidation"]


@dataclass
class Liquidation:
    discriminator: typing.ClassVar = 5
    @classmethod
    def to_json(cls) -> LiquidationJSON:
        return LiquidationJSON(
            kind="Liquidation",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "Liquidation": {},
        }



class OrderFilledWithAMMJSON(typing.TypedDict):
    kind: typing.Literal["OrderFilledWithAMM"]


@dataclass
class OrderFilledWithAMM:
    discriminator: typing.ClassVar = 6
    @classmethod
    def to_json(cls) -> OrderFilledWithAMMJSON:
        return OrderFilledWithAMMJSON(
            kind="OrderFilledWithAMM",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "OrderFilledWithAMM": {},
        }



class OrderFilledWithAMMJitJSON(typing.TypedDict):
    kind: typing.Literal["OrderFilledWithAMMJit"]


@dataclass
class OrderFilledWithAMMJit:
    discriminator: typing.ClassVar = 7
    @classmethod
    def to_json(cls) -> OrderFilledWithAMMJitJSON:
        return OrderFilledWithAMMJitJSON(
            kind="OrderFilledWithAMMJit",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "OrderFilledWithAMMJit": {},
        }



class OrderFilledWithMatchJSON(typing.TypedDict):
    kind: typing.Literal["OrderFilledWithMatch"]


@dataclass
class OrderFilledWithMatch:
    discriminator: typing.ClassVar = 8
    @classmethod
    def to_json(cls) -> OrderFilledWithMatchJSON:
        return OrderFilledWithMatchJSON(
            kind="OrderFilledWithMatch",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "OrderFilledWithMatch": {},
        }



class OrderFilledWithMatchJitJSON(typing.TypedDict):
    kind: typing.Literal["OrderFilledWithMatchJit"]


@dataclass
class OrderFilledWithMatchJit:
    discriminator: typing.ClassVar = 9
    @classmethod
    def to_json(cls) -> OrderFilledWithMatchJitJSON:
        return OrderFilledWithMatchJitJSON(
            kind="OrderFilledWithMatchJit",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "OrderFilledWithMatchJit": {},
        }



class MarketExpiredJSON(typing.TypedDict):
    kind: typing.Literal["MarketExpired"]


@dataclass
class MarketExpired:
    discriminator: typing.ClassVar = 10
    @classmethod
    def to_json(cls) -> MarketExpiredJSON:
        return MarketExpiredJSON(
            kind="MarketExpired",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "MarketExpired": {},
        }



class RiskingIncreasingOrderJSON(typing.TypedDict):
    kind: typing.Literal["RiskingIncreasingOrder"]


@dataclass
class RiskingIncreasingOrder:
    discriminator: typing.ClassVar = 11
    @classmethod
    def to_json(cls) -> RiskingIncreasingOrderJSON:
        return RiskingIncreasingOrderJSON(
            kind="RiskingIncreasingOrder",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "RiskingIncreasingOrder": {},
        }



class ReduceOnlyOrderIncreasedPositionJSON(typing.TypedDict):
    kind: typing.Literal["ReduceOnlyOrderIncreasedPosition"]


@dataclass
class ReduceOnlyOrderIncreasedPosition:
    discriminator: typing.ClassVar = 12
    @classmethod
    def to_json(cls) -> ReduceOnlyOrderIncreasedPositionJSON:
        return ReduceOnlyOrderIncreasedPositionJSON(
            kind="ReduceOnlyOrderIncreasedPosition",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "ReduceOnlyOrderIncreasedPosition": {},
        }



class OrderFillWithSerumJSON(typing.TypedDict):
    kind: typing.Literal["OrderFillWithSerum"]


@dataclass
class OrderFillWithSerum:
    discriminator: typing.ClassVar = 13
    @classmethod
    def to_json(cls) -> OrderFillWithSerumJSON:
        return OrderFillWithSerumJSON(
            kind="OrderFillWithSerum",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "OrderFillWithSerum": {},
        }



class NoBorrowLiquidityJSON(typing.TypedDict):
    kind: typing.Literal["NoBorrowLiquidity"]


@dataclass
class NoBorrowLiquidity:
    discriminator: typing.ClassVar = 14
    @classmethod
    def to_json(cls) -> NoBorrowLiquidityJSON:
        return NoBorrowLiquidityJSON(
            kind="NoBorrowLiquidity",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "NoBorrowLiquidity": {},
        }



class OrderFillWithPhoenixJSON(typing.TypedDict):
    kind: typing.Literal["OrderFillWithPhoenix"]


@dataclass
class OrderFillWithPhoenix:
    discriminator: typing.ClassVar = 15
    @classmethod
    def to_json(cls) -> OrderFillWithPhoenixJSON:
        return OrderFillWithPhoenixJSON(
            kind="OrderFillWithPhoenix",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "OrderFillWithPhoenix": {},
        }



class OrderFilledWithAMMJitLPSplitJSON(typing.TypedDict):
    kind: typing.Literal["OrderFilledWithAMMJitLPSplit"]


@dataclass
class OrderFilledWithAMMJitLPSplit:
    discriminator: typing.ClassVar = 16
    @classmethod
    def to_json(cls) -> OrderFilledWithAMMJitLPSplitJSON:
        return OrderFilledWithAMMJitLPSplitJSON(
            kind="OrderFilledWithAMMJitLPSplit",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "OrderFilledWithAMMJitLPSplit": {},
        }



class OrderFilledWithLPJitJSON(typing.TypedDict):
    kind: typing.Literal["OrderFilledWithLPJit"]


@dataclass
class OrderFilledWithLPJit:
    discriminator: typing.ClassVar = 17
    @classmethod
    def to_json(cls) -> OrderFilledWithLPJitJSON:
        return OrderFilledWithLPJitJSON(
            kind="OrderFilledWithLPJit",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "OrderFilledWithLPJit": {},
        }



class DeriskLpJSON(typing.TypedDict):
    kind: typing.Literal["DeriskLp"]


@dataclass
class DeriskLp:
    discriminator: typing.ClassVar = 18
    @classmethod
    def to_json(cls) -> DeriskLpJSON:
        return DeriskLpJSON(
            kind="DeriskLp",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "DeriskLp": {},
        }



class OrderFilledWithOpenbookV2JSON(typing.TypedDict):
    kind: typing.Literal["OrderFilledWithOpenbookV2"]


@dataclass
class OrderFilledWithOpenbookV2:
    discriminator: typing.ClassVar = 19
    @classmethod
    def to_json(cls) -> OrderFilledWithOpenbookV2JSON:
        return OrderFilledWithOpenbookV2JSON(
            kind="OrderFilledWithOpenbookV2",
        )

    @classmethod
    def to_encodable(cls) -> dict:
        return {
            "OrderFilledWithOpenbookV2": {},
        }





OrderActionExplanationKind = typing.Union[
None,
InsufficientFreeCollateral,
OraclePriceBreachedLimitPrice,
MarketOrderFilledToLimitPrice,
OrderExpired,
Liquidation,
OrderFilledWithAMM,
OrderFilledWithAMMJit,
OrderFilledWithMatch,
OrderFilledWithMatchJit,
MarketExpired,
RiskingIncreasingOrder,
ReduceOnlyOrderIncreasedPosition,
OrderFillWithSerum,
NoBorrowLiquidity,
OrderFillWithPhoenix,
OrderFilledWithAMMJitLPSplit,
OrderFilledWithLPJit,
DeriskLp,
OrderFilledWithOpenbookV2,
]
OrderActionExplanationJSON = typing.Union[
NoneJSON,
InsufficientFreeCollateralJSON,
OraclePriceBreachedLimitPriceJSON,
MarketOrderFilledToLimitPriceJSON,
OrderExpiredJSON,
LiquidationJSON,
OrderFilledWithAMMJSON,
OrderFilledWithAMMJitJSON,
OrderFilledWithMatchJSON,
OrderFilledWithMatchJitJSON,
MarketExpiredJSON,
RiskingIncreasingOrderJSON,
ReduceOnlyOrderIncreasedPositionJSON,
OrderFillWithSerumJSON,
NoBorrowLiquidityJSON,
OrderFillWithPhoenixJSON,
OrderFilledWithAMMJitLPSplitJSON,
OrderFilledWithLPJitJSON,
DeriskLpJSON,
OrderFilledWithOpenbookV2JSON,
]

def from_decoded(obj: dict) -> OrderActionExplanationKind:
    if not isinstance(obj, dict):
        raise ValueError("Invalid enum object")
    if "None" in obj:
      return None()
    if "InsufficientFreeCollateral" in obj:
      return InsufficientFreeCollateral()
    if "OraclePriceBreachedLimitPrice" in obj:
      return OraclePriceBreachedLimitPrice()
    if "MarketOrderFilledToLimitPrice" in obj:
      return MarketOrderFilledToLimitPrice()
    if "OrderExpired" in obj:
      return OrderExpired()
    if "Liquidation" in obj:
      return Liquidation()
    if "OrderFilledWithAMM" in obj:
      return OrderFilledWithAMM()
    if "OrderFilledWithAMMJit" in obj:
      return OrderFilledWithAMMJit()
    if "OrderFilledWithMatch" in obj:
      return OrderFilledWithMatch()
    if "OrderFilledWithMatchJit" in obj:
      return OrderFilledWithMatchJit()
    if "MarketExpired" in obj:
      return MarketExpired()
    if "RiskingIncreasingOrder" in obj:
      return RiskingIncreasingOrder()
    if "ReduceOnlyOrderIncreasedPosition" in obj:
      return ReduceOnlyOrderIncreasedPosition()
    if "OrderFillWithSerum" in obj:
      return OrderFillWithSerum()
    if "NoBorrowLiquidity" in obj:
      return NoBorrowLiquidity()
    if "OrderFillWithPhoenix" in obj:
      return OrderFillWithPhoenix()
    if "OrderFilledWithAMMJitLPSplit" in obj:
      return OrderFilledWithAMMJitLPSplit()
    if "OrderFilledWithLPJit" in obj:
      return OrderFilledWithLPJit()
    if "DeriskLp" in obj:
      return DeriskLp()
    if "OrderFilledWithOpenbookV2" in obj:
      return OrderFilledWithOpenbookV2()
    raise ValueError("Invalid enum object")

def from_json(obj: OrderActionExplanationJSON) -> OrderActionExplanationKind:
    if obj["kind"] == "None":
        return None()
    if obj["kind"] == "InsufficientFreeCollateral":
        return InsufficientFreeCollateral()
    if obj["kind"] == "OraclePriceBreachedLimitPrice":
        return OraclePriceBreachedLimitPrice()
    if obj["kind"] == "MarketOrderFilledToLimitPrice":
        return MarketOrderFilledToLimitPrice()
    if obj["kind"] == "OrderExpired":
        return OrderExpired()
    if obj["kind"] == "Liquidation":
        return Liquidation()
    if obj["kind"] == "OrderFilledWithAMM":
        return OrderFilledWithAMM()
    if obj["kind"] == "OrderFilledWithAMMJit":
        return OrderFilledWithAMMJit()
    if obj["kind"] == "OrderFilledWithMatch":
        return OrderFilledWithMatch()
    if obj["kind"] == "OrderFilledWithMatchJit":
        return OrderFilledWithMatchJit()
    if obj["kind"] == "MarketExpired":
        return MarketExpired()
    if obj["kind"] == "RiskingIncreasingOrder":
        return RiskingIncreasingOrder()
    if obj["kind"] == "ReduceOnlyOrderIncreasedPosition":
        return ReduceOnlyOrderIncreasedPosition()
    if obj["kind"] == "OrderFillWithSerum":
        return OrderFillWithSerum()
    if obj["kind"] == "NoBorrowLiquidity":
        return NoBorrowLiquidity()
    if obj["kind"] == "OrderFillWithPhoenix":
        return OrderFillWithPhoenix()
    if obj["kind"] == "OrderFilledWithAMMJitLPSplit":
        return OrderFilledWithAMMJitLPSplit()
    if obj["kind"] == "OrderFilledWithLPJit":
        return OrderFilledWithLPJit()
    if obj["kind"] == "DeriskLp":
        return DeriskLp()
    if obj["kind"] == "OrderFilledWithOpenbookV2":
        return OrderFilledWithOpenbookV2()
    kind = obj["kind"]
    raise ValueError(f"Unrecognized enum kind: {kind}")

layout = EnumForCodegen(
"None" / borsh.CStruct(),
"InsufficientFreeCollateral" / borsh.CStruct(),
"OraclePriceBreachedLimitPrice" / borsh.CStruct(),
"MarketOrderFilledToLimitPrice" / borsh.CStruct(),
"OrderExpired" / borsh.CStruct(),
"Liquidation" / borsh.CStruct(),
"OrderFilledWithAMM" / borsh.CStruct(),
"OrderFilledWithAMMJit" / borsh.CStruct(),
"OrderFilledWithMatch" / borsh.CStruct(),
"OrderFilledWithMatchJit" / borsh.CStruct(),
"MarketExpired" / borsh.CStruct(),
"RiskingIncreasingOrder" / borsh.CStruct(),
"ReduceOnlyOrderIncreasedPosition" / borsh.CStruct(),
"OrderFillWithSerum" / borsh.CStruct(),
"NoBorrowLiquidity" / borsh.CStruct(),
"OrderFillWithPhoenix" / borsh.CStruct(),
"OrderFilledWithAMMJitLPSplit" / borsh.CStruct(),
"OrderFilledWithLPJit" / borsh.CStruct(),
"DeriskLp" / borsh.CStruct(),
"OrderFilledWithOpenbookV2" / borsh.CStruct(),
)
