'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh;
import typing;
from anchorpy.borsh_extension import BorshPubkey;
from construct import Container;
from dataclasses import dataclass;
from solders.pubkey import Pubkey;
from solders.sysvar import RENT;

class RFQOrderIdJSON(typing.TypedDict):
    uuid: list[int]
    maxTs: int

@dataclass
class RFQOrderId:
    layout: typing.ClassVar = borsh.CStruct(
        "uuid" /borsh.U8[8],
        "maxTs" /borsh.I64,
        )
    #fields
    uuid: list[int]
    maxTs: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "RFQOrderId":
        return cls(
                   uuid=obj.uuid,
                   maxTs=obj.maxTs,
                )

    #def to_encodable(self) -> dict[str, typing.Any]:
    #    return {"row": self.row, "column": self.column}

    def to_json(self) -> RFQOrderIdJSON:
        return {
                "uuid": self.uuid,
                "maxTs": self.maxTs,
        }

    @classmethod
    def from_json(cls, obj: RFQOrderIdJSON) -> "RFQOrderId":
        return cls(
                uuid=obj["uuid"],
                maxTs=obj["maxTs"],
        )






