'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey, EnumForCodegen
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey


class ExternalMarketJSON(typing.TypedDict):
    kind: typing.Literal["ExternalMarket"]


@dataclass
class ExternalMarket:
    discriminator: typing.ClassVar = 0
    def to_json(self) -> ExternalMarketJSON:
        return ExternalMarketJSON(
            kind="ExternalMarket",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "ExternalMarket": {},
        }



MatchJSONValue = tuple[str,int]
MatchValue = tuple[SolPubkey,int]

class MatchJSON(typing.TypedDict):
    kind: typing.Literal["Match"]
    value: MatchJSONValue


@dataclass
class Match:
    discriminator: typing.ClassVar = 1
    value : MatchValue
    def to_json(self) -> MatchJSON:
        return MatchJSON(
            kind="Match",
            value = (str(self.value[0]),self.value[1],)
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "Match": { "item_0":self.value[0],"item_1":self.value[1] }
        }





SpotFulfillmentMethodKind = typing.Union[
    ExternalMarket,
    Match,
]
SpotFulfillmentMethodJSON = typing.Union[
    ExternalMarketJSON,
    MatchJSON,
]

def from_decoded(obj: dict) -> SpotFulfillmentMethodKind:
    if not isinstance(obj, dict):
        raise ValueError("Invalid enum object")
    if "ExternalMarket" in obj:
      return ExternalMarket()
    if "Match" in obj:
      val = obj["Match"]
      return Match((
      val["item_0"],val["item_1"],
      ))
    raise ValueError("Invalid enum object")

def from_json(obj: SpotFulfillmentMethodJSON) -> SpotFulfillmentMethodKind:
    if obj["kind"] == "ExternalMarket":
        return ExternalMarket()

    if obj["kind"] == "Match":
        matchJSONValue = typing.cast(MatchJSONValue, obj["value"])
        return Match(
        (SolPubkey.from_string(matchJSONValue[0]),matchJSONValue[1],)
        )

    kind = obj["kind"]
    raise ValueError(f"Unrecognized enum kind: {kind}")


layout = EnumForCodegen(
"ExternalMarket" / borsh.CStruct(),
"Match" / borsh.CStruct("item_0" / BorshPubkey,"item_1" / borsh.U16,),
)
